### ISSUE TITLE
SqlExecutorStep: allowed commands

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#1]
According to [https://github.com/sogis/gretl/blob/master/src/main/java/ch/so/agi/gretl/steps/SqlExecutorStep.java#L259](https://github.com/sogis/gretl/blob/master/src/main/java/ch/so/agi/gretl/steps/SqlExecutorStep.java#L259) only INSERT, UPDATE or DELETE is allowed.

`CREATE EXTENSION postgis;` works.
`SELECT UpdateGeometrySRID('afu_gws', 'public_aww_gszoar','the_geom',2056);` does not work and throws error.

**Comment by edigonzales** [comment]
`CREATE SCHEMA IF NOT EXISTS afu_gws;` works.

**Comment by edigonzales** [comment]
Ist `executeUpdate()` the appropriate method?

**Comment by claeis** [comment]
m.E. nein, besser execute()

**Comment by edigonzales** [comment]
- Versuchen, dass sinnvoller Logging-Output bewahrt werden kann.
- Umgang mit SELECT-ResultSets momentan out-of-scope.
