### ISSUE TITLE
logging vereinfachen

### ISSUE THREAD

**Issue by claeis** [sogis/gretl-v1#11]
Grundsätzliche Frage: behalten wir eine eigenes Logger Interface? Oder verwenden wir SLF4J oder das Gradle-Logging-Interface?
Falls wir das Eigene behalten, kann man die Implemetierung m.E. trotzdem vereinfachen.

**Comment by ojeker** [comment]
Eher eigenes behalten. Wie besprochen sicherstellen dass es in beiden "Environments" loggt. (Unittest Env, Gradle integrated)
