### ISSUE TITLE
[Inbetriebnahme] Script Approval funktioniert noch nicht

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#113]
Das _Script Approval_ funktioniert noch nicht. Beim ersten Start des gretl-job-generator wurde mir gemeldet, dass das Skript dieses Jobs nicht _approved_ sei. Müssen die Hashes in https://github.com/sogis/openshift-jenkins/blob/master/configuration/scriptApproval.xml angepasst werden?

Wo gibt es Doku, wie man die Hashes erzeugt?

Weshalb braucht es 2 Hashes?

**Comment by schmandr** [comment]
Workaround: Die Konfigurationsansicht des _gretl-job-generator_ öffnen und das Häkchen _Use Groovy Sandbox_ setzen und wieder entfernen. Dann die Konfiguration speichern.

**Comment by chrira** [comment]
Leider wird der Hash bei jeder Installation anders installiert.

Auf meinem Repo ist die Überprüfung ausgeschaltet: https://github.com/chrira/openshift-jenkins

Euer Fork hat noch die alte Struktur der Jobs, welche für die System-Tests nicht funktioniert. Bitte euer Repo mit dem Master Branch von meinem Repo updaten.

**Comment by schmandr** [comment]
Der sogis-Fork ist nun ebenfalls aktualisiert. Der Job _gretl-job-generator_ läuft nun problemlos.
