### ISSUE TITLE
[Inbetriebnahme] Ist Jenkins Ephemeral das richtige Image?

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#115]
https://github.com/sogis/gretl/blob/master/serviceConfig/templates/jenkins-s2i-template.json nutzt _Jenkins Ephemeral_. Das bedeutet vermutlich, dass nach einem Neustart des Pods die Build History (und damit die Logs der letzten Job-Ausführungen) verloren geht. Dazu steht

> "WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing."

**Comment by chrira** [comment]
Genau, Ephemeral ist ein stateless Template. Das ist für Testumgebungen okey aber nicht für Produktion.

Ich habe im serviceConfig ein persistent Template eingefügt und die Dokumentation zum Erstellen erweitert. Mit diesem Template werden alle Konfigurationen und Build Informationen vom Jenkins auf ein Persistet Volume geschrieben. Somit überleben diese Daten Restarts vom Container.
Beim Anwenden vom Template die gewünschte Grösse vom Persistent Volume angeben (VOLUME_CAPACITY Parameter).

**Comment by schmandr** [comment]
Danke, das funktioniert.

Aus Interesse (es kommt mir nicht drauf an): Was ist der Grund, dass du die Templates von json zu yaml geändert hast?
