### ISSUE TITLE
[Inbetriebnahme] Wie definiert man den Zeitplan, wann ein GRETL-Job jeweils ausgeführt werden soll?

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#118]
Kann man das im _gretl-job.groovy_ eintragen? Wie muss das aussehen?

**Comment by chrira** [comment]
Ja, das wird im gretl-job.groovy eingetragen. Der Job muss einmal laufen, damit er im Jenkins den Zeitplan aktiviert oder akuralisiert.
Hier gibt es bereits ein Beispiel: [gretl/inttest/jobs/iliValidator/gretl-job.groovy](https://github.com/sogis/gretl/blob/master/gretl/inttest/jobs/iliValidator/gretl-job.groovy)

Pipeline Trigger Referenz: https://jenkins.io/doc/book/pipeline/syntax/#triggers

Auszug aus der [Jenkins Dokumentation](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/triggers/TimerTrigger/help-spec.jelly):

This field follows the syntax of cron (with minor differences). Specifically, each line consists of 5 fields separated by TAB or whitespace: MINUTE HOUR DOM MONTH DOW
MINUTE	Minutes within the hour (0–59)
HOUR	The hour of the day (0–23)
DOM	The day of the month (1–31)
MONTH	The month (1–12)
DOW	The day of the week (0–7) where 0 and 7 are Sunday.

**Comment by schmandr** [comment]
Funktioniert.

Damit ich mir dessen später immer noch bewusst bin, halte ich hier nochmal fest:

> Der Job muss einmal laufen, damit er im Jenkins den Zeitplan aktiviert oder aktualisiert.

Zudem meldet Jenkins, wenn man sich einen der generierten Jobs anzeigt:

_This item has been changed manually since it was generated by the seed job._ 

Davon darf man sich nicht beirren lassen; damit ist eben gemeint, dass der Zeitplan, der vor der ersten Ausführung nicht wirklich gesetzt war und nur im Pipeline Script festgehalten war, nun gesetzt ist. In diesem Zusammenhang steht auch die folgende Warnung, die beim Ausführen des generierten Jobs ausgegeben wird:

_WARNING: The properties step will remove all JobPropertys currently configured in this job, either from the UI or from an earlier properties step.
This includes configuration for discarding old builds, parameters, concurrent builds and build triggers._

**Comment by schmandr** [comment]
Jetzt gibt es hier aber ein Problem:
Nach dem ersten Ausführen eines generierten Jobs ist sein Zeitplan aktiviert, so wie wir das ja wollen. Wenn nun aber der Job _gretl-job-generator_ das nächste mal gelaufen ist (er läuft ja alle 8 Stunden), ist der Zeitplan des generierten Jobs wieder weg. Das ist natürlich nicht so, wie es sein sollte. Was wäre eine Lösung hierfür?

**Comment by chrira** [comment]
Es gitb 2 Lösungen für das Problem:
- Multibranch Pipeline
- Trigger in Properties File auslagern

### Multibranch Pipeline
Vorteil:
Es kann das oben referenzierte Beispiel verwendet werden. Alle Trigger und sonstigen Konfigurationen sind möglich. Dies aus dem Grund, da der Job nach der Generierung 1x ausgeführt wird.

Nachteil:
Alle Jobs werden, nach dem der Seeder-Job sie neu generiert hat, ein mal ausgeführt.
Im Jenkins Gui gibt es eine Verschachtelung, da es pro Job immer einen Multibranch Job / Folder gibt, worin sich dann der eigentliche Job befindet. (doppelte Anzahl an Jobs)

### Properties File
Im Seeder Job werden die Trigger direckt in der Job DSL angelegt und nicht mehr im groovy File vom GRETL-Job. Somit werden sie mit dem Job generiert und sofort aktiv. Siehe Job DSL [Doku](https://jenkinsci.github.io/job-dsl-plugin/#path/pipelineJob-triggers)
Ein Properties File in jedem GRETL-Job Folder definiert gewisse Konfigurationen. So können z.B Cron Trigger denfiniert werden.
Beispiel Properties Datei:
`trigger.cron="H 12 * * 1-5"`

Vorteil:
Generierung der Trigger vom Seeder Job -> sofort aktiv

Nachteil:
Nicht alle Konfigurationen möglich.
Komplexe Logik im Seeder Job zum Auslesen und Generieren der Konfigurationen (Falls nur der Cron Trigger benutzt wird, ist es rasch umgesetzt)
Log Rotation (löschen alter Builds) müsste ähnlich zum Cron Trigger implementiert werden.

**Comment by schmandr** [comment]
Demnach wäre die Variante mit Properties-File für uns die bessere.

Wir brauchen voraussichtlich die Eigenschaften
* Zeitplan
* Log Rotation
* E-Mail-Versand, z.B. nachdem ein Job durchgelaufen ist, mit dem Plugin "Email Extension"
* evtl. "Starte Build, nachdem andere Projekte gebaut wurden"

Ich träumte auch mal von der Definition von Berechtigungen, im Zusammenhang mit LDAP-Anbindung usw. usw. Das könnenwir aber vorläufig aussen vor lassen, und mittelfristig haben wir für die Zugriffskontrolle voraussichtlich ohnehin einen anderen Weg.

**Comment by schmandr** [comment]
Hmm. Habe herausgefunden, wie das im Seeder Job aussehen würde im Fall eines hart codierten Beispiels. Schwierig wird nun tatsächlich die "Komplexe Logik im Seeder Job zum Auslesen und Generieren der Konfigurationen"...
```
[...]
pipelineJob(realJobName) {
    triggers {
      	cron('H 12 * * 1-5')
    }
    logRotator {
        numToKeep(20)
    }
    definition {
        cps {
            script(releaseScript)
            sandbox()
        }
    }
  }
[...]
```

**Comment by schmandr** [comment]
Habe hier etwas hingekriegt, was ich nun noch umsetzen muss:
```
def releaseScript = readFileFromWorkspace(pipelineFil)

Properties properties = new Properties()
File propertiesFile = new File(base + '/' + realJobName + '/job.properties')
propertiesFile.withInputStream {
  properties.load(it)
}

pipelineJob(realJobName) {
  logRotator {
      numToKeep(properties."logRotator.numToKeep" as Integer)
  }
  triggers {
      cron(properties."triggers.cron")
  }
  definition {
      cps {
          script(releaseScript)
          sandbox()
      }
  }
}
```
oder (verstehe ich besser):
```
def properties = new Properties()
def propertiesFile = new File(base + '/' + realJobName + '/job.properties')
properties.load(propertiesFile.newDataInputStream())

pipelineJob(realJobName) {
  logRotator {
      numToKeep(properties.getProperty('logRotator.numToKeep') as Integer)
  }
  triggers {
      cron(properties.getProperty('triggers.cron'))
  }
  definition {
      cps {
          script(releaseScript)
          sandbox()
      }
  }
}

```

**Comment by schmandr** [comment]
Bessere Version (wobei die Einrückung noch nicht passt; und man natürlich das Eine oder Andere per Umgebungsvariable konfigurierbar machen könnte):

```
  def properties = new Properties(['logRotator.numToKeep':'15'])
  def propertiesFile = new File(base + '/' + realJobName + '/job.properties')
  if (propertiesFile.exists()) {
    properties.load(propertiesFile.newDataInputStream())
  }
  
  if (properties.getProperty('triggers.cron') == null) {
    pipelineJob(realJobName) {
    	logRotator {
        	numToKeep(properties.getProperty('logRotator.numToKeep') as Integer)
    	}
    	definition {
        	cps {
            	script(releaseScript)
            	sandbox()
        	}
    	}
  	}
  } else {
    pipelineJob(realJobName) {
    	logRotator {
        	numToKeep(properties.getProperty('logRotator.numToKeep') as Integer)
    	}
    	triggers {
      		cron(properties.getProperty('triggers.cron'))
    	}
      	definition {
        	cps {
            	script(releaseScript)
            	sandbox()
        	}
    	}
  	}
  }
```

**Comment by schmandr** [comment]
Umgesetzt mit Properties File: https://github.com/sogis/openshift-jenkins/commit/3ce14f05dbc9b731f339c27cdf94c8973c6f59cf
