### ISSUE TITLE
[Inbetriebnahme] Wie nimmt man einen neue Image-Tag ("Version") in Betrieb?

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#120]
In https://github.com/sogis/gretl/blob/master/serviceConfig/README.md steht auf der letzten Zeile

> This can also be used to update the GRETL runtime image after creation.

Wenn man den angegebenen Befehl aber ein weiteres Mal ausführt mit einem neuen Image-Tag ("Version"), wird gemeldet:

```
The ImageStream "gretl" is invalid: 
* []: Internal error: imagestreams "gretl" is invalid: spec.tags[latest].from.name: Invalid value: "sogis/gretl-runtime:32": must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>
* spec.tags[latest].from.kind: Required value: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag'
```

Ich musste zuerst `oc delete is gretl` ausführen, aber das geht vermutlich auch eleganter.

**Comment by chrira** [comment]
Update mit apply hat bei mir funktioniert.

Habe die Dokumentation mit "oc patch" und manuellem Update in der OpenShift Web Konsole ergänzt.

**Comment by schmandr** [comment]
Gut. Die Variante mit `oc patch` funktioniert bei mir.
