### ISSUE TITLE
Optional Annotation

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#21]
Soll diese für die Properties in den Custom Tasks verwendet werden?

[https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Optional.html](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Optional.html)

**Comment by claeis** [comment]
yes, should be used where appropriate

**Comment by edigonzales** [comment]
Background: I needed to figure out which input parameters I really have to set (= mandatory) with the ili2pg tasks. The tasks run without any problems even when there is no input parameter set:

`task replaceDataset (type: Ili2pgReplace) {}`

My really first thought was that the task should complain about missing input parameters.
