### ISSUE TITLE
setupPgExt not working

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#26]
`task initDatabase(type: Ili2pgImportSchema) {`
    `description  = "Creates database schema and empty tables."`
    `database = ["jdbc:postgresql://"+dbHost+":"+dbPort+"/"+dbDatabase, dbUser, dbPass]`
    `dbschema = dbSchema`
    `models = modelName`
    `disableValidation = true`
    `defaultSrsCode = "2056"`
    `smart1Inheritance = true`
    `createBasketCol = true`
    `createDatasetCol = true`
    `sqlEnableNull = true`
    `importTid = true`
    `nameByTopic = true`
    `createEnumTabs = true`
    `setupPgExt = true`
    `// Can be a transfer file, a local ili file or`
    `// the model name.`
    `iliFile = modelName`
`}`

Führt zu folgendem Fehler:

`Info: driverVersion <42.1.3>`
`failed to run ili2pg`
`java.lang.IllegalStateException: failed to get PostGIS version`

Eventuell weil die Connection jetzt von extern kommt: [https://github.com/sogis/gretl/blob/master/src/main/java/ch/so/agi/gretl/tasks/impl/Ili2pgAbstractTask.java#L146](https://github.com/sogis/gretl/blob/master/src/main/java/ch/so/agi/gretl/tasks/impl/Ili2pgAbstractTask.java#L146)

`CREATE EXTENSION` steckt in `PgCustomStrategy.postConnect()`: [https://github.com/claeis/ili2db/blob/06239885d0710057056df594ee316668a98e3fb5/ili2pg/src/ch/ehi/ili2pg/PgCustomStrategy.java#L51](https://github.com/claeis/ili2db/blob/06239885d0710057056df594ee316668a98e3fb5/ili2pg/src/ch/ehi/ili2pg/PgCustomStrategy.java#L51)

Diese Methode wird aber nicht aufgerufen, wenn die Connection von extern kommt: [https://github.com/claeis/ili2db/blob/1212f82155e16d930dfbe64dc72bbecc0e62af4b/src/ch/ehi/ili2db/base/Ili2db.java#L168](https://github.com/claeis/ili2db/blob/1212f82155e16d930dfbe64dc72bbecc0e62af4b/src/ch/ehi/ili2db/base/Ili2db.java#L168)

**Comment by claeis** [comment]
see claeis/ili2db#121

**Comment by claeis** [comment]
fixed in ili2pg>=3.10.9
