### ISSUE TITLE
ili2pg tasks should have trace logging option

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#28]

**Comment by claeis** [comment]
independent of gradle logging settings? (My proposal: link it to the gradle log level)

**Comment by edigonzales** [comment]
If possible link it to the gradle log level.

**Comment by claeis** [comment]
Use gradle option -i to see the normal ili2pg/ilivalidater log (use gradle option -d to see ili2pg/ilivalidator  --trace output).
