### ISSUE TITLE
db2db step: Enable Oracle as source DBMS

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#3]
Enable Oracle as source DBMS in db2db step.

**Comment by ojeker** [comment]
- Write automated tests
- Jars to artifactory

**Comment by edigonzales** [comment]
Ich habe einen neuen Branch erstellt (oracle-db-branch). Das "Freischalten" der Oracle-JDBC im Code ist kein Problem. Fragen stellen sich:

* Wo liegt die Oracle-JDBC.jar?
* Wie wird getestet?

Die Oracle-JDBC.jar liegt jetzt im gretl/lib-Verzeichnis. Irgendein instabiles oder privates Artifactory haben für mich mehr Nachteile. Im build.gradle musste die Abhängigkeit so formuliert werden, dass diese ans POM durchgereicht wird. Ansonsten weiss das Plugin nicht, dass es die Oracle-JDBC.jar benötigt. Zusätzlich brauchte es einen Task der die Jar-Datei dann auch tatsächlich in ein lokales Maven-Repo deployed. Dieser Task muss beim Erstellen der Gretl-Runtime berücksichtigt werden.

Für die Tests habe ich im `tooling`-Ordner ein zusätzliches Shell-Skript erstellt, das eine Oracle-Db als Docker-Container startet. Dabei habe ich die bestehenden Postgres-Sachen jeweils ergänzt mit "-pg". -> Hat eventuell Auswirkungen in der Pipeline. Bitte überprüfen. Eine weitere "fette" Datenbank kommt mindestens ja noch hinzu (sql server), daher sollte die Files etc. entsprechend benannt werden.

Tests selber habe noch keine geschrieben. Das kommt noch.

**Comment by edigonzales** [comment]
Diskussion mit @uncoyote:

Nur ein System-Test machen.  Dazu braucht es einen Oracle-DB-Pod in Openshift (@uncoyote mit @bjsvwpfe ) und einen (oder zwei) kleine Jobs und ein wenig Code. Beim Paketieren des Images muss jetzt auch noch die Oracle-JDBC.jar berücksichtig werden.

Wenn es geht den System-Test manuell ausführen/testen und notfalls wieder ignorieren, falls Pod noch nicht vorhanden ist.

**Comment by edigonzales** [comment]
* runtimeImage/ angepasst wegen lokaler oracle jdbc jar.
* docker image build ausgeführt.
* Job "dbTasks_OracleLibsPresent" erstellt (analog PostgreSQL)
* Docker Oracle DB gestartet. (start-test-database-ora.sh).
* `./start-gretl.sh --job_directory /Users/stefan/Projekte/gretl-oracle-db-branch/gretl/inttest/jobs/dbTasks_OracleLibsPresent/ -Pgretltest_dburi=jdbc:oracle:thin:@10.0.1.4:1521:xe` -> erfolgreich
* Zwei Tests (analog PostgreSQL) in JenkinsTest.java. Test noch ignoriert, da noch keine Oracle-DB in Openshift
