### ISSUE TITLE
Vereinheitlichung Input-Parameter dataFile bei ili2pg-Tasks

### ISSUE THREAD

**Issue by barpastu** [sogis/gretl-v1#34]
Es wäre schön, wenn der Input-Parameter dataFile bei allen ili2pg-Tasks den gleichen Datentyp verlangen würde. Aufgefallen ist mir dies bei ili2pgImport (verlangt Pfad zum dataFile) und bei ili2pgReplace (verlangt dataFile als File).

Bei ili2pgImport:
```
@InputFile 
public Object dataFile=null;
```

Bei ili2pgReplace:
```
@InputFile 
public File dataFile=null;
```

**Comment by claeis** [comment]
Object ist glaub die bessere/richtigere Variante, damit man die verschiedenen Varianten für Dateiangaben im gradle Skript verwenden kann.
