### ISSUE TITLE
CsvImport: Primary-Key-Attribut

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#55]
Frage: Gibt es eine Möglichkeit, die Daten in eine Tabelle zu importieren, die im Vergleich zum CSV ein zusätzliches Primary-Key-Attribut hat? (Da ein CSV das nicht zwingend hat.) Oder muss man das durch nachträglichen Datenumbau erreichen?

**Comment by claeis** [comment]
Das müsste funktionieren (wenn die zusätzlichen Spalten NULLable sind oder einen default Wert haben (bei PK mit SERIAL der Fall))
