### ISSUE TITLE
DB-Verbindung wird nicht SSL-verschlüsselt aufgebaut

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#56]
Betrifft wohl nicht nur den CSV-Import, ist mir aber hier aufgefallen:
Die Verbindung zur DB wird nicht SSL-verschlüsselt hergestellt, d.h. ein DB-Server, der nur SSL-verschlüsselte Verbindungen akzeptiert, meldet folgenden Fehler:
```
:importCsvConnection error: 
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "nnn.nnn.nnn.nnn", user "uuuu", database "dbdbdb", SSL off
```

**Comment by claeis** [comment]
m.E. andere JDBC URL verwenden...(ssl=true)
