### ISSUE TITLE
CsvExport: Frage zur Reihenfolge der Attribute

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#57]
Frage: Der Export sortiert die Attribute alphabetisch. Ist das bewusst oder unbewusst so? (Hängt auch davon ab, wie der CsvValidator sich verhält: ist ihm die Attributreihenfolge egal? Dem CSV-Import zumindest schon.)

**Comment by claeis** [comment]
Das ist bewusst so (damit man nicht jedesmal ein anderes CSV erhält). Aber müsste man m.E. per Konfiguration übersteuern können.
