### ISSUE TITLE
Db2Db-Step: Vorgängiges Löschen des Tabelleninhaltes funktioniert nicht.

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#6]
`new TransferSet("copyAdagis_Flaechen.sql", 'ada_adagis_a.flaechenfundstellen', true)`

Sollte m.E. aus der Tabelle `ada_adagis_a.flaechenfundstellen` vor dem Reinkopieren alles löschen. Funktioniert bei mir nicht.

**Comment by pfeimich** [comment]
Confirmed.
Bei mir auch nicht

**Comment by edigonzales** [comment]
[https://github.com/sogis/gretl/blob/8dbebf52746bb9036282f5e13609572e2cc79cfd/src/main/java/ch/so/agi/gretl/steps/TransferSet.java#L28](https://github.com/sogis/gretl/blob/8dbebf52746bb9036282f5e13609572e2cc79cfd/src/main/java/ch/so/agi/gretl/steps/TransferSet.java#L28)

Should be:

`this.deleteAllRows = outputDeleteAllRows;`

**Comment by EchoCharlie85** [comment]
fixed. 

- fixed  this.deleteAllRows
- fixed DeleteTest
- added delete-controll to delete-methode. If after delete the table is not empty, an exception will be thrown!

**Comment by pfeimich** [comment]
Also bei mir stolpert er aktuell über doppelte pkeys. Sieht also nicht so aus als ob er vorgängig löscht.
```
* What went wrong:
Execution failed for task ':transferAfuAltlasten'.
> Inner Exception Message: Batch entry 0 INSERT INTO afu_altlasten_pub.altlasten_belastete_standorte_internet (data_id, wkb_geometry, vflz_combined_id_kt, c_vflz_vftyp, c_vflz_unterstand, c_vflz_bearbstand, bel_teilfl, c_bere_res_abwbewe, max_bel, max_bel_text) VALUES (6507683, '0106000020080800000100000001030000000100000009000000A557C69CD5CF4341C6E263399FB83241A947B779DBCF434118513A99A3B83241BED78877E4CF4341E797D98CA9B832419A99BEB0E5CF434168A71D5FAAB83241E26EC830EBCF43413EB5524083B832411D435AF8E2CF43410AE0D5027FB83241BAEAA3B4DDCF43412CFAD0B59DB8324141409AC2D6CF4341016FF01498B83241A557C69CD5CF4341C6E263399FB83241', '22.007.0804U', 'Unfallstandort', 'Eintrag im KbS', 'abgeschlossen', 'belastet, nicht untersuchungsbed?rftig', '02', '5', 'belastet, nicht untersuchungsbed??rftig') was aborted: ERROR: duplicate key value violates unique constraint "altlasten_belastete_standorte_data_id_pkey"
    Detail: Key (data_id)=(6507683) already exists.  Call getNextException to see other errors in the batch.
```

**Comment by EchoCharlie85** [comment]
Also. Ich habe das ganze hier bei mir nachgebaut. Ich versuche mit dem SQL-files, welches Michael geschickt hat, die gewünschten Daten vom geodb in die Tabelle auszug_akt_altlasten17785.altlasten_belastete_standorte auf geodb-t zu schreiben. Dabei erhalte ich folgenden Fehler: 

Requested attribute [bel_teilfl] is not contained in this AttributeNameMap.

Soweit ich dies rekonstruieren kann, kommt dieser Fehler daher, dass die durch das SQL-file erzeugte Spalten nicht mit denjenigen der Zieltabelle übereinstimmen. bel_teilfl existiert z.B. in der Zieltabelle schlicht nicht.

**Comment by EchoCharlie85** [comment]
Ich habe folgenden Test geschrieben: 

    public void MichaelTest() throws Exception {

        ArrayList<TransferSet> mylist = new ArrayList<TransferSet>();

        File sqlfile = new File("/home/bjsvwsch/codebasis/gretlv1/src/test/resources/michaeltest.sql");
        mylist.add(new TransferSet(
                sqlfile.getPath(), "afu_altlasten_pub.altlasten_belastete_standorte_internet", new Boolean(true)
        ));

        Connector sourceDb = new Connector("jdbc:postgresql://geodb.verw.rootso.org/sogis", "bjsvwsch", null);
        Connector targetDb = new Connector("jdbc:postgresql://geodb-t.verw.rootso.org/sogis", "bjsvwsch", null);

        Db2DbStep db2db = new Db2DbStep();
        //db2dbstep ausführen
        db2db.processAllTransferSets(sourceDb, targetDb, mylist);

    }

Bei mir im lokalen GRETL funktioniert es so.

**Comment by pfeimich** [comment]
fixed mit v1.0.2
