### ISSUE TITLE
CsvValidator: Datumsformat

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#60]
Der CSV-Validator meldet:
`invalid format of date value <15.11.2016>`
Ist es so, dass nur das Format  «2016-11-15» geht? (Das ist hier eher mal eine Frage.)

**Comment by claeis** [comment]
Aktuell geht beim CvsImport Tag-Monat-Jahr (und als Trennzeichen geht alternativ auch ``.`` oder ``:`` oder ``,``. (Aber muesste man beim CvsImport m.E. konfigurieren können)
Beim CvsValidator muss es im Csv-File so sein, wie es im ili1/ITF oder ili2/XTF formatiert wäre.
