### ISSUE TITLE
CsvValidator: Boolean-Werte

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#61]
Ist es so, dass nur ‘true’ und ‘false’ gehen? Wie ist es mit ‘t’ und ‘f’ und 0 und 1? (Ist primär mal eine Frage. Vielleicht ist es ja sogar besser, wenn nur 1 Variante geht.)

**Comment by claeis** [comment]
CsvImport: Aktuell wird ``t``,``true``,``y``,``yes``,``on``,``1`` als TRUE aufgefasst/importiert. Alles Andere als FALSE.

CsvValidator: Nur ``true`` oder ``false`` sind zulässige Werte
