### ISSUE TITLE
Code-Einrückung

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#63]
Die Einrückung des Codes ist teilweise noch nicht einheitlich, z.B. bei 
https://github.com/sogis/gretl/blob/61500170d290bbe615f6c67e05699da45c85e041/src/main/java/ch/so/agi/gretl/tasks/CsvImport.java#L88-L98
Aber auch an verschiedenen anderen Stellen.

**Comment by claeis** [comment]
Dürfen Tabs im Source verwendet werden? Falls ja, mit wieviel Leerzeichen werden sie dargestellt?
