### ISSUE TITLE
Verzeichnisse "steps" und "tasks"

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#64]
Was ist eigentlich der Grund dafür, dass einige Steps unter _.../ch/so/agi/gretl/tasks_ und andere unter _.../ch/so/agi/gretl/steps_ liegen?

**Comment by claeis** [comment]
Ich haette gerne alle Tasks unter ../gretl/tasks (also die gradle wrapper zu den Steps; aber keine Steps). Aber ich wollte Eurer bestehenden Scripts nicht beschaedigen. Aber man sollte die bald verschieben.
