### ISSUE TITLE
String, mit welchem sich GRETL bei der DB identifiziert, genauer definieren

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#65]
GRETL identifiziert sich an der DB mit _PostgreSQL JDBC Driver_ (ersichtlich, wenn man während der Ausführung eines Steps `SELECT application_name FROM pg_stat_activity();` ausführt).
Kann dies z.B. auf _gretl_ geändert werden, damit z.B. bei Fehleranalysen auf der DB klarer ersichtlich ist, von welcher Anwendung eine bestimmte Query oder Connection stammt?

**Comment by claeis** [comment]
Das muss via entsprechenden JDBC connection URL gemacht werden. (``jdbc:postgresql://localhost/test?ApplicationName=gretl``). Also nur Config, keine Software-Anpassung.

https://jdbc.postgresql.org/documentation/94/connect.html#connection-parameters
