### ISSUE TITLE
ShpValidator: Wenn Spalten fehlen, wird dies nicht als Fehler gemeldet

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#69]
ShpValidator müsste einen Fehler melden, wenn dem Shapefile eine Spalte komplett fehlt, die gemäss Modell da sein müsste, aber deren Attributwerte nicht MANDATORY sind.

**Comment by claeis** [comment]
Aber der ShpImport sollte auch funktionieren, wenn eine Spalte in der DB vorhanden ist, die im shp-File nicht vorhanden ist, oder?

**Comment by schmandr** [comment]
Ja, genau. Der Import muss trotzdem funktionieren. Das heisst:
Wenn bei der Prüfung das Shape weniger Attribute hat als die Vergleichsklasse des Modells, muss die Prüfung einen Fehler melden.
Wenn beim Import das Shape weniger Attribute hat als die Zieltabelle, muss der Import trotzdem funktionieren.

Das ist so schon konsistent, oder?
