### ISSUE TITLE
Kryptische Fehlermeldung wenn Leerzeile am Ende in Transferset

### ISSUE THREAD

**Issue by pfeimich** [sogis/gretl-v1#7]
Wenn man nach einem mit Semikolon abgeschlossenen SQL Befehl noch eine Leerzeile im Transferset hat gibt es die Fehlermeldung

```
Execution failed for task ':transferAfuGewaesserschutz'.
> Inner Exception Message: null
```

Bitte entweder vernünftige Fehlermeldung oder am Besten gleich die Leerzeile ignorieren

**Comment by edigonzales** [comment]
Mit `-i` wird ein `DELETE succesfull` ausgegeben. Ist das sinnvoll, da die Geschichte in einer Transaktion läuft und es nicht gelöscht wird, falls der Kopier-Teil des Tasks in die Hose geht.

Ansonsten noch Typo korrigieren: `successful`.
