### ISSUE TITLE
ShpValidator: Datumswerte werden nicht erkannt

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#70]
Meldung:
```
invalid format of date value <Mon Jul 25 00:00:00 UTC 2016>
invalid format of date value <Thu Sep 29 00:00:00 UTC 2016>
invalid format of date value <Fri Sep 23 00:00:00 UTC 2016>
```
Im Shapefile sehen sie eigentlich gut aus:
```
2016-07-25
2016-09-29
2016-09-23
```

**Comment by claeis** [comment]
Mit ogr2ogr und pgsql2shp erhalte ich für einen timestamp unterschiedliche Daten!

    ADATE (Date) = 2013/10/21
    ATIMESTAMP (String) = 2015-02-16 08:35:45

Im anderen Fall (ogr2ogr):

    ADATE (Date) = 2013/10/21
    ATIMESTAMP (Date) = 2015/02/16

D.h. ich kann nicht erkennen, ob eine Spalte ein Timestamp ist (obwohl man das gem. DBASE Format durchaus könnte...). 

- Soll ich bei einem String via Datums-Formatierung (welches Muster?) versuchen zu  lesen, falls es gem. ili-Modell ein INTERLIS.XMLDateTime, INTERLIS.XMLDate oder INTERLIS.XMLTime Attribut ist?

- Soll ich ein Date auch als Timestamp lesen oder als Fehler interpretieren?

**Comment by schmandr** [comment]
Schwierige Fragen... Und ich muss unbedingt los. Überlege mir etwas am Donnerstag.

**Comment by claeis** [comment]
- Date wurde korrigiert
- Timestamp wird aktuell nicht weiterverfolgt (evtl. bei Gelegenheit abklären, ob das ein DBase Feature ist, das von ArcGIS gar nicht unterstütz wird.)
