### ISSUE TITLE
ShpValidator: Boolean-Werte werden nicht erkannt

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl-v1#71]
Meldung:
```
value <f> is not a BOOLEAN
value <t> is not a BOOLEAN
value <yes> is not a BOOLEAN
```
Es funktioniert mit _false_ und _true_.
Das Verhalten muss wohl gleich sein wie gemäss #61.

**Comment by claeis** [comment]
Mit ogr2ogr und pgsql2shp erhalte ich unterschiedliche Daten!

    ABOOLEAN (String) = T

Im anderen Fall (ogr2ogr):

    ABOOLEAN (Integer) = 1

D.h. ich kann nicht erkennen, ob eine Spalte ein Boolean ist (obwohl man das gem. DBASE Format durchaus könnte...). Soll ich einfach T und 1 als TRUE, und F und 0 als FALSE, lesen, falls es gem. ili-Modell eine Boolean Attribut ist?

**Comment by schmandr** [comment]
> Soll ich einfach T und 1 als TRUE, und F und 0 als FALSE, lesen, falls es gem. ili-Modell eine Boolean Attribut ist?

Hm, ja ist wohl sinnvoll. Aber müssten wir wegen der Konsistenz zum CsvValidator nicht zusätzlich auch noch `true` und `false` aufnehmen?
Und Vielleicht macht es eine andere Anwendung (ArcGIS, FME) ja nochmal anders?
