### ISSUE TITLE
Probleme mit encoding bei db2db step

### ISSUE THREAD

**Issue by pfeimich** [sogis/gretl-v1#8]
Wenn man in einem SQL File eine Query mit Umlauten drin hat (z.B. Case When ... Then 'ü....' erscheinen in der Ziel-DB die Umlaute falsch.
[afu_altlasten_pub_altlasten_belastete_standorte_internet.txt](https://github.com/sogis/gretl/files/1303371/afu_altlasten_pub_altlasten_belastete_standorte_internet.txt)

Systemumgebung (Vagrant Maschine)

```
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_CH.UTF-8
LC_TIME=de_CH.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_CH.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_CH.UTF-8
LC_NAME=de_CH.UTF-8
LC_ADDRESS=de_CH.UTF-8
LC_TELEPHONE=de_CH.UTF-8
LC_MEASUREMENT=de_CH.UTF-8
LC_IDENTIFICATION=de_CH.UTF-8
LC_ALL=
```
file -i ergibt 

`text/plain; charset=utf-8`

Encoding DB 

```
CREATE DATABASE sogis
  WITH OWNER = sogis_admin
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'de_CH.UTF-8'
       LC_CTYPE = 'de_CH.UTF-8'
       CONNECTION LIMIT = -1;
```

**Comment by edigonzales** [comment]
Bei mir funktionierts.

macOS und PostgreSQL bei AWS.

```
stefan@SemucChampey:~/tmp/gretl-test$ locale
LANG="de_CH.UTF-8"
LC_COLLATE="de_CH.UTF-8"
LC_CTYPE="de_CH.UTF-8"
LC_MESSAGES="de_CH.UTF-8"
LC_MONETARY="de_CH.UTF-8"
LC_NUMERIC="de_CH.UTF-8"
LC_TIME="de_CH.UTF-8"
LC_ALL="de_CH.UTF-8"
```

```
SELECT pg_encoding_to_char(encoding) FROM pg_database WHERE datname = 'xanadu2';
```

```
UTF8
```

SQL-File ist auch UTF8 (immerhin zeigt es Editor "Visual Code Studio") so an.

Query:

```
SELECT 
	CASE WHEN 1=1 THEN 'übrige'::text END as fubar

```

**Comment by edigonzales** [comment]
Eventuell hilft

`sqlFileReader = new InputStreamReader(sqlFileInputStream, "UTF8");`

anstatt: [https://github.com/sogis/gretl/blob/master/src/main/java/ch/so/agi/gretl/util/SqlReader.java#L39](https://github.com/sogis/gretl/blob/master/src/main/java/ch/so/agi/gretl/util/SqlReader.java#L39)

**Comment by pfeimich** [comment]
Funktioniert noch immer nicht.
Beispiel Datei ist angehängt.
Vielleicht kann mal jmd die Datei testen, der gretl lokal laufen hat?
Schema ist in der Test-Db angelegt von geodb nach geodb-t sollte also funktionieren.
[test.sql.txt](https://github.com/sogis/gretl/files/1318044/test.sql.txt)
Damit ihr auch wisst wohin die Tabelle in geodb-t gespielt werden soll hier noch das build.gradle
[build.gradle.txt](https://github.com/sogis/gretl/files/1318285/build.gradle.txt)

**Comment by edigonzales** [comment]
@bjsvwpfe Kannst du das versuchen:

`gradle -Dfile.encoding=UTF8`

**Comment by pfeimich** [comment]
Funktioniert. Danke
