### ISSUE TITLE
Artifactory publish

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#9]
Reicht für das AIO-Repository der Code im `build.gradle`?

Für mein Artifactory-Repository benötige ich immer:

```
plugins {
    id "com.jfrog.artifactory" version "4.5.2"
}

apply plugin: 'com.jfrog.artifactory'

artifactory {
    contextUrl = gretlRepoUrl
    publish {
        repository {
            repoKey = repo
            username = gretlRepoWriterName
            password = gretlRepoWriterPass
            maven = true
        }
        defaults {
            publications ('mavenJava')
        }
    }
}
publishing {
    publications {
        mavenJava(MavenPublication) {
			from components.java 
        }
    }
}
```

**Comment by ojeker** [comment]
Ja, das reicht - hat auch auf beim jfrog temp account bestens funktioniert.

**Comment by claeis** [comment]
dünkt mich falsch, wenn ein public Projekt in ein privates Repo publiziert...

**Comment by edigonzales** [comment]
privat == nicht sichtbar 
oder
privat != (jcenter || mavencentral)

?

**Comment by claeis** [comment]
privat = nicht sichtbar (bzw. nur mit usrid/pwd via internet zugreifbar)

**Comment by edigonzales** [comment]
Ja. M.E. eine Übergangslösung. Beim AIO deponiert, dass für mich ein Repo im Internet (lesen ohne login/pwd) wichtig resp. matchentscheidend ist.
