### ISSUE TITLE
Cannot build gretl

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#91]
* What went wrong:
Could not resolve all files for configuration ':gretl:compileClasspath'.
> Could not find ch.interlis:iox-ili:1.20.2.
  Searched in the following locations:
      file:/home/stefan/.m2/repository/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      file:/home/stefan/.m2/repository/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      http://jars.interlis.ch/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      http://jars.interlis.ch/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      http://download.osgeo.org/webdav/geotools/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      http://download.osgeo.org/webdav/geotools/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      https://repo1.maven.org/maven2/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      https://repo1.maven.org/maven2/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
  Required by:
      project :gretl
      project :gretl > ch.interlis:ili2pg:3.11.1
      project :gretl > ch.interlis:iox-wkf:1.0.0
> Could not find ch.interlis:iox-ili:1.20.2.
  Searched in the following locations:
      file:/home/stefan/.m2/repository/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      file:/home/stefan/.m2/repository/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      http://jars.interlis.ch/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      http://jars.interlis.ch/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      http://download.osgeo.org/webdav/geotools/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      http://download.osgeo.org/webdav/geotools/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      https://repo1.maven.org/maven2/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      https://repo1.maven.org/maven2/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
  Required by:
      project :gretl > ch.interlis:ilivalidator:1.6.0
> Could not find ch.interlis:iox-ili:1.20.2.
  Searched in the following locations:
      file:/home/stefan/.m2/repository/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      file:/home/stefan/.m2/repository/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      http://jars.interlis.ch/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      http://jars.interlis.ch/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      http://download.osgeo.org/webdav/geotools/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      http://download.osgeo.org/webdav/geotools/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
      https://repo1.maven.org/maven2/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.pom
      https://repo1.maven.org/maven2/ch/interlis/iox-ili/1.20.2/iox-ili-1.20.2.jar
  Required by:
      project :gretl > ch.interlis:ilivalidator:1.6.0 > ch.interlis:ili2c-tool:4.7.7-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
2 actionable tasks: 1 executed, 1 up-to-date

Mir ist nicht ganz klar woher die Version 1.20.2 kommt? Muss irgendwo in den "+" stecken vielleicht? Oder Feenstaub.

**Comment by claeis** [comment]
Feenstaub....sollte jetzt gehen (gradle dependencies zeigt die Abhängigkeiten; iox-ili-1.20.2 wird von ili2c-tool-4.7.7 referenziert, war aber noch nicht publiziert)
