### ISSUE TITLE
gradle tasks --all funktioniert via Docker-Image nicht

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl-v1#97]
`./start-gretl.sh --docker_image sogis/gretl-runtime:30 --job_directory /Users/stefan/Projekte/oevkov-tests/gretl/ --task_name tasks --all`

`--all` wird nicht als an gradle weitergeleitet.

**Comment by schmandr** [comment]
Ist gelöst mit https://github.com/sogis/gretljobs/commit/0228abee2487849b55a2a99acca71b5c307a8a7a. Allerdings im `start-gretl.sh` des _gretljobs_-Repos; dieses ist ja dasjenige, das man als GRETL-Job-Entwickler tatsächlich verwendet. Das `start-gretl.sh` des _gretl_-Repos (dieses wird für Tests in Travis verwendet) belassen wir vorläufig so, bis sich zeigt, dass es dieselben Anpassungen ebenfalls benötigt.
